[[redirects]]
  from = "/*"
  to = "/public/*"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods: "GET"
    Content-Type: "application/json"